### ISSUE TITLE
Chiseled Blocks not Dropping Bits

### ISSUE THREAD

**Issue by SilverKytten** [Aeltumn/Chisels-and-Bits-2#18]
Is this a Forge version mismatch or have I corrupted something?

[latest.log](https://github.com/Aeltumn/Chisels-and-Bits-2/files/3906548/latest.log)
![2019-11-29_17 49 24](https://user-images.githubusercontent.com/2188185/69892986-1a7bb080-12d1-11ea-9e8b-b3d452d7130b.png)
![2019-11-29_17 49 13](https://user-images.githubusercontent.com/2188185/69892987-1a7bb080-12d1-11ea-9d04-0c534202cc42.png)

**Comment by Aeltumn** [comment]
As noted in [differences file](https://github.com/Aeltumn/Chisels-and-Bits-2/blob/1.14/alpha/DIFFERENCES.md) bits as items don't exist anymore. You need a bit storage (currently only the bit bag suffices) to collect bits.

I removed bits as items because they had too major problems in my opinion:
- When working with a big variety of blocks, inventory management would become a nightmare.
- Bits took up many item ids, which didn't matter that much in 1.12 when we had metadata ids, but now with every item being a seperate item I don't want to tank the performance by adding so many extra items.
