### ISSUE TITLE
When will there be another update?

### ISSUE THREAD

**Issue by zzzpixelflamezzz** [Aeltumn/Chisels-and-Bits-2#35]
This mod is going very well so far. I'm just wondering when and how often will there be updates.

**Comment by Aeltumn** [comment]
I'm very busy with some other projects and I haven't had as much time the last few months but I'm determined to work on the mod whenever I've go time. There will be new updates/releases whenever they are ready.

**Comment by Ynaught** [comment]
With covid-19 going around, any chance you have more time to work on this? It causes the game to crash alot in 1.14 with some chisel blocks not rendering.

**Comment by Aeltumn** [comment]
> 
> 
> With covid-19 going around, any chance you have more time to work on this? It causes the game to crash alot in 1.14 with some chisel blocks not rendering.

The quarantine unfortunately won't really increase the time I get to spend on development, but I have had some time this week to finally start the 1.15 updates. I've already got quite a bit of free time but there are too many paid projects taking up my time right now that are more important to work on than on the mod.

Unfortunately though I can't fix those crashes in 1.14 right now, it's a very complicated fundamental issue that I think is due to some major internal changes in Forge 1.13+. These crashes do however, as far as I know, only occur on some startups, not on every startup. So if you keep trying to start eventually it will start and the crashes won't occur at all.

**Comment by Ynaught** [comment]
It's not a start up crash, it's a rendering crash where some chisel blocks are invisible and will crash if I try to interact with them.

**Comment by Aeltumn** [comment]
Please give me the (crash) logs for your issue then, I'll see if I can fix those.

**Comment by Ynaught** [comment]
It seams to not agree with my shader. I turned shaders off and it rendered in, no crashing. Normally it crashes AFTER I interact with a block that won't render. Now I turn the shader back on, it still won't render, but when I interact with it, my game won't crash, now it's just not crashing but still invisible. This is weird because I have resource pacts that act similar to shaders and THEY don't cause any issues.

**Comment by Aeltumn** [comment]
Shaders are currently not supported so I'm not surprised they cause a crash. You're going to have to disable your shaders to use C&B2 for now.

**Comment by Ynaught** [comment]
Hate to tell you this man, but your mod kinda only exists to make things look pretty. Shaders are kinda the pinnacle of making this look pretty, So it would be counter productive to trade a 10 for a 7, if one has to be disabled, it's gonna be the mod as it just doesn't do as much for the esthetic as shaders do. You said "for now", so please let me know when we can look past this counter-intuitiveness and this purpose (that being esthetics) breaking bug is fixed.

Oh, and think you for the quick replies all the same.

**Comment by Aeltumn** [comment]
So the 1.14 version of this mod uses basically the exact same rendering code from the original mod, (C&B was originally made by AlgorithmX2, not me) I thought the original mod supported shaders but maybe I broke them while porting the old system. However, I started work on this mod without ever having made a mod before and without any knowledge of rendering. I understand the current rendering system conceptually but I really have no clue how shaders works or more importantly what needs to change in the code to make shaders work.
The current rendering code has a lot of problems besides not supporting shaders and since 1.15 required me to change a fair amount of it anyways I decided to just rewrite all rendering code from scratch so that I can do more about rendering issues in the future than just poking the code with a stick until it works.
I'm currently in the process of learning how rendering works by rewriting the tape measure and I'm probably going to give the radial menu a complete redesign while I'm at it. I'm happy with the progress I've made but it'll likely take until the end of summer to get the chiseled blocks themselves to render at all, let alone make them shader compatible.

So, once I've got the mod on 1.15 and properly understand the rendering I can have a look at how shaders work and what I can do to make them work. _Also because of the changes in 1.15 shaders will need to be changed themselves too so that's going to make everything even more different._

**Comment by Ynaught** [comment]
Oh, so you're an up and coming modder then, well done. It was so clean that I thought you were the original guy. Since you're not, if I may, I do a bit of programming myself, though I may know a few different languages, I never got around to java or whatever language mods/shaders use. I'd be more than willing to help aid you in figuring this out if you wish. I would need a week or so to learn the fundamentals but learning things like this has never been an issue for me in the past when I put my mind to it. All I'd really need is your insight with working on this mod to work off of.
