### ISSUE TITLE
I want to help you <3

### ISSUE THREAD

**Issue by SpelliCosta** [Aeltumn/Chisels-and-Bits-2#36]
Hello I am a big fan of chisel & bits, I was saddened that the creator of the mids stopped updating it but I see that you have taken the mod to update it and its I am very grateful to you really. So I come to you to offer my help to do "The pre-alpha tester" I am a builder who likes minecraft for this building rating which can bring but with chisel and bits it is another level of build that I can bring , and during this confinement time I want to help. And I could do its live on twitch because I would like to create a minecraft community and nothing of it than your mods in preview to show another build rating on minecraft.

Thank you very much for taking over the mods.

I remain at your disposal and courrage to you for the containment and that your family is in good health.

<3

**Comment by Aeltumn** [comment]
Thanks for the offer, you're very welcome to try out the latest builds here on github and give me feedback. I'm really interested in making the workflow easier and adding small things to make everything that little bit better. Like bags being much larger or making it quicker to change modes.
I don't really have pre-alpha builds, every bit of work I do on C&B is uploaded straight to this git repository so if you follow the progress on this repository you'll be able to use the latest version that exists.

I'll let you know actually when the first functional builds for 1.15 are done because the curseforge page could use some pretty pictures (with credit ofc) of the things you can build, and I'm not much of a builder myself.
