### ISSUE TITLE
What is the difference between "merge" and "overlap" mode when placing models?

### ISSUE THREAD

**Issue by Tompouce-onGit** [Aeltumn/Chisels-and-Bits-2#43]
I tried a bunch of different things trying to figure out the difference, but I still haven't figured it out.
Did I miss something, or has it not been implemented fully yet?
Edit: In fact, what do any of the modes do? I can't figure it out :/

**Comment by Aeltumn** [comment]
These two apply when you place a chiseled block into an existing chiseled block. Merge removes bits from the block you're placing whilst overlap removes bits from the block that's already been placed. 
So for example if you have a wooden log placed down with a hole in it and you put down a chiseled slime block in that blockspace with merge you'll get a log with slime in the hole but on overlap you'll get an entire slime block.

Grid is a special one, it places the chiseled block like any normal block, placing it next to it instead of merging the chiseled blocks.

Fit is how the mod used to work in 1.12, you can only place chiseled blocks into an existing chiseled block when no bits overlap. _However, I think this one is bugged and behaves identical to merge right now._

**Comment by Tompouce-onGit** [comment]
Thank you for the clarification!
I would maybe suggest more evocative names for merge and overlap, because when I first saw them I thought it was a "either have two chiseled blocks share the same block space, or fuse them into one block" sort of situation. I think names like "add" and "replace" for merge and overlap respectively would be more suggestive of their effect, or maybe "place under" and "place over" as an analog to organising images in layers in a word processor.
Just a thought though.
