### ISSUE TITLE
Mod is not working

### ISSUE THREAD

**Issue by SalviaUnga** [Aeltumn/Chisels-and-Bits-2#5]
I've compiled this mod in my IntelliJ IDEA, but in game, it is not working. Chisel not chiseling and not placing blocks. Maybe I wrong compiled mod?

**Comment by Aeltumn** [comment]
That's correct, in 1.14 a lot of forge was rewritten and I'm still waiting on code I've submitted to Forge to get added to restore features that Chisels & Bits uses. This includes that currently the chisel item doesn't do anything. At this point all items have been added as dummy items and the Left+Alt menu is nearly finished. (icons in the Left+Alt menus aren't rendering because Forge doesn't support that right now, also has a PR pending)

**Comment by SalviaUnga** [comment]
Ok, thanks. Will be waiting.
