### ISSUE TITLE
Fabric version?

### ISSUE THREAD

**Issue by Mhowser** [Aeltumn/Chisels-and-Bits-2#8]
Will C&B2 ever have a Fabric version?

**Comment by Aeltumn** [comment]
Not soon, maybe in the future.

I personally don't get the need to port mods to fabric, I'm happy with Forge and the features/support that it offers so I don't see the need to switch "platforms". Additionally, simultaneously working on both Forge and Fabric versions is a hassle.

**Comment by zzzpixelflamezzz** [comment]
why can't you just install forge?

**Comment by Mhowser** [comment]
because we want to use our other fabric mods too!

**Comment by Aeltumn** [comment]
> 
> 
> why can't you just install forge?

Though I do not have the time (or knowledge about Fabric) to work on a Fabric version I don't agree with telling people to "just use Forge". If Fabric keeps going strong I'll probably check it out at some point and if it turns out making a Fabric version of C&B won't take years of work I'm not against making it at all, it's just that I don't really get how Fabric works and I'm familiar with Forge so that's my go-to.

To get back to answering your message, it's very natural for people to ask for a version on another platform, lots of people ask pc game X to make an xbox or playstation port. I've got no problem with people doing so unless they are being impolite or spamming. Modders spent many hours on their mods and I really dislike how many players are so impolite and spamming modders about not having their mod updated to the latest version.
_I like rambling so don't mind me typing an essay here.._

**Comment by Mhowser** [comment]
Fabric is a new modloader that is lightweight and modular, it does not use the MCP mappings but instead uses Yarn mappings which are free for all to use. https://fabricmc.net

**Comment by Jarfeh** [comment]
There is a project called patchwork, that's currently attempting to port forge mappings to fabric to allow forge mods to run under fabric loader. I wonder if that could be used in some way
